package com.cpyt.model;
// Generated 26/10/2017 01:18:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCur;
     private Persona persona;
     private String nomCur;
     private String desCur;
     private BigDecimal preCur;
     private String traCur;
     private Set inscripcions = new HashSet(0);
     private Set leccioneses = new HashSet(0);

    public Curso() {
    }

	
    public Curso(Persona persona, String nomCur, String desCur, BigDecimal preCur, String traCur) {
        this.persona = persona;
        this.nomCur = nomCur;
        this.desCur = desCur;
        this.preCur = preCur;
        this.traCur = traCur;
    }
    public Curso(Persona persona, String nomCur, String desCur, BigDecimal preCur, String traCur, Set inscripcions, Set leccioneses) {
       this.persona = persona;
       this.nomCur = nomCur;
       this.desCur = desCur;
       this.preCur = preCur;
       this.traCur = traCur;
       this.inscripcions = inscripcions;
       this.leccioneses = leccioneses;
    }
   
    public Integer getIdCur() {
        return this.idCur;
    }
    
    public void setIdCur(Integer idCur) {
        this.idCur = idCur;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNomCur() {
        return this.nomCur;
    }
    
    public void setNomCur(String nomCur) {
        this.nomCur = nomCur;
    }
    public String getDesCur() {
        return this.desCur;
    }
    
    public void setDesCur(String desCur) {
        this.desCur = desCur;
    }
    public BigDecimal getPreCur() {
        return this.preCur;
    }
    
    public void setPreCur(BigDecimal preCur) {
        this.preCur = preCur;
    }
    public String getTraCur() {
        return this.traCur;
    }
    
    public void setTraCur(String traCur) {
        this.traCur = traCur;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }
    public Set getLeccioneses() {
        return this.leccioneses;
    }
    
    public void setLeccioneses(Set leccioneses) {
        this.leccioneses = leccioneses;
    }




}


