package com.cpyt.model;
// Generated 26/10/2017 01:18:47 AM by Hibernate Tools 4.3.1



/**
 * Lecciones generated by hbm2java
 */
public class Lecciones  implements java.io.Serializable {


     private Integer idLec;
     private Curso curso;
     private String nomLec;
     private String vidLec;
     private String arcLec;

    public Lecciones() {
    }

    public Lecciones(Curso curso, String nomLec, String vidLec, String arcLec) {
       this.curso = curso;
       this.nomLec = nomLec;
       this.vidLec = vidLec;
       this.arcLec = arcLec;
    }
   
    public Integer getIdLec() {
        return this.idLec;
    }
    
    public void setIdLec(Integer idLec) {
        this.idLec = idLec;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNomLec() {
        return this.nomLec;
    }
    
    public void setNomLec(String nomLec) {
        this.nomLec = nomLec;
    }
    public String getVidLec() {
        return this.vidLec;
    }
    
    public void setVidLec(String vidLec) {
        this.vidLec = vidLec;
    }
    public String getArcLec() {
        return this.arcLec;
    }
    
    public void setArcLec(String arcLec) {
        this.arcLec = arcLec;
    }




}


