package com.cpyt.model;
// Generated 26/10/2017 01:18:47 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPer;
     private String dni;
     private String apaterno;
     private String amaterno;
     private String nombres;
     private String correo;
     private String celular;
     private String direccion;
     private String cip;
     private String imgCol;
     private int estado;
     private Set usuarios = new HashSet(0);
     private Set inscripcions = new HashSet(0);
     private Set cursos = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String dni, String apaterno, String amaterno, String nombres, String correo, String celular, String direccion, String imgCol, int estado) {
        this.dni = dni;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.nombres = nombres;
        this.correo = correo;
        this.celular = celular;
        this.direccion = direccion;
        this.imgCol = imgCol;
        this.estado = estado;
    }
    public Persona(String dni, String apaterno, String amaterno, String nombres, String correo, String celular, String direccion, String cip, String imgCol, int estado, Set usuarios, Set inscripcions, Set cursos) {
       this.dni = dni;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.nombres = nombres;
       this.correo = correo;
       this.celular = celular;
       this.direccion = direccion;
       this.cip = cip;
       this.imgCol = imgCol;
       this.estado = estado;
       this.usuarios = usuarios;
       this.inscripcions = inscripcions;
       this.cursos = cursos;
    }
   
    public Integer getIdPer() {
        return this.idPer;
    }
    
    public void setIdPer(Integer idPer) {
        this.idPer = idPer;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCip() {
        return this.cip;
    }
    
    public void setCip(String cip) {
        this.cip = cip;
    }
    public String getImgCol() {
        return this.imgCol;
    }
    
    public void setImgCol(String imgCol) {
        this.imgCol = imgCol;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


