package com.cpyt.model;
// Generated 26/10/2017 01:18:47 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer idTar;
     private String numTar;
     private String fecVen;
     private String numCvv;
     private BigDecimal saldo;

    public Tarjeta() {
    }

    public Tarjeta(String numTar, String fecVen, String numCvv, BigDecimal saldo) {
       this.numTar = numTar;
       this.fecVen = fecVen;
       this.numCvv = numCvv;
       this.saldo = saldo;
    }
   
    public Integer getIdTar() {
        return this.idTar;
    }
    
    public void setIdTar(Integer idTar) {
        this.idTar = idTar;
    }
    public String getNumTar() {
        return this.numTar;
    }
    
    public void setNumTar(String numTar) {
        this.numTar = numTar;
    }
    public String getFecVen() {
        return this.fecVen;
    }
    
    public void setFecVen(String fecVen) {
        this.fecVen = fecVen;
    }
    public String getNumCvv() {
        return this.numCvv;
    }
    
    public void setNumCvv(String numCvv) {
        this.numCvv = numCvv;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }




}


