package com.cpyt.model;
// Generated 26/10/2017 01:18:47 AM by Hibernate Tools 4.3.1



/**
 * TrabajoFinal generated by hbm2java
 */
public class TrabajoFinal  implements java.io.Serializable {


     private Integer idTra;
     private Inscripcion inscripcion;
     private String arcTra;
     private String desTra;
     private int notTra;

    public TrabajoFinal() {
    }

    public TrabajoFinal(Inscripcion inscripcion, String arcTra, String desTra, int notTra) {
       this.inscripcion = inscripcion;
       this.arcTra = arcTra;
       this.desTra = desTra;
       this.notTra = notTra;
    }
   
    public Integer getIdTra() {
        return this.idTra;
    }
    
    public void setIdTra(Integer idTra) {
        this.idTra = idTra;
    }
    public Inscripcion getInscripcion() {
        return this.inscripcion;
    }
    
    public void setInscripcion(Inscripcion inscripcion) {
        this.inscripcion = inscripcion;
    }
    public String getArcTra() {
        return this.arcTra;
    }
    
    public void setArcTra(String arcTra) {
        this.arcTra = arcTra;
    }
    public String getDesTra() {
        return this.desTra;
    }
    
    public void setDesTra(String desTra) {
        this.desTra = desTra;
    }
    public int getNotTra() {
        return this.notTra;
    }
    
    public void setNotTra(int notTra) {
        this.notTra = notTra;
    }




}


